openapi: 3.0.0
info:
  title: ATS-pemrograman-iii
  version: 1.0.0
servers:
  - url: http://localhost:8082/
components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: Bearer
paths:
  /categories:
    get:
      tags:
        - default
      summary: Get-Data
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    post:
      tags:
        - default
      summary: Add-Data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                category: t-shirt
                about: "semua ada kaos"
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    put:
      tags:
        - default
      summary: Update-Data
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                id: 1
                category: laptop
                about: "segala laptop"
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /categories?id={id}:
    get:
      tags:
        - default
      summary: Get-Data-ID
      parameters:
        - name: id
          in: query
          required: true
          schema:
            type: integer
            example: 1
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
    delete:
      tags:
        - default
      summary: Delete-Data
      parameters:
        - name: id
          in: path # Mengubah 'query' menjadi 'path'
          required: true
          schema:
            type: integer
            example: 2
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
  /login:
    post:
      tags:
        - default
      summary: Login
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                username: test
                password: test too
      responses:
        "200":
          description: Successful response
          content:
            application/json: {}
